local ls = require('luasnip')
vim.keymap.set({ "i", "s" }, "<C-x>", function()
  ls.expand_or_jump()
end, {silent = true})
vim.keymap.set({ "i", "s" }, "<C-n>", function()
  ls.change_choice(1)
end, {silent = true})
vim.keymap.set({ "i", "s" }, "<C-p>", function()
  ls.change_choice(-1)
end, {silent = true})
vim.keymap.set({ "i", "s" }, "<C-l>", function()
  ls.jump(1)
end, {silent = true})
vim.keymap.set({ "i", "s" }, "<C-j>", function()
  ls.jump(-1)
end, {silent = true})
