require('nvim-surround').setup()
require('Comment').setup()
require('gitsigns').setup()
require("colorizer").setup()
require("nvim-autopairs").setup()
require('nvim-ts-autotag').setup()
require("mason").setup()
